apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocr-service.fullname" . }}-config
  labels:
    {{- include "ocr-service.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.db.host | quote }}
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
