apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ocr-service.fullname" . }}-secret
  labels:
    {{- include "ocr-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
